### ISSUE TITLE
✨ Test case design

### ISSUE THREAD

**Issue by zhumeisongsong** [zhumeisongsong/react-url-image-downloader#3]
- [x] Show an image, src=url (#7)
- [x] Add download button with click event (#9 )
- [x] Add fetch image logic to download event (#11)
- [ ] Add hover event to image for showing the download button
